[cursor.style]
shape = "Block"

[mouse]
hide_when_typing = true

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "regular"

[window]
dimensions = { columns = 120, lines = 35 }
opacity = 0.9
title = "Alacritty :)"

[window.padding]
x = 5
y = 5

# proper tmux colors
[env]
TERM = "xterm-256color"

# Colors (One Dark)

# Default colors
[colors.primary]
background = '#282c34'
foreground = '#abb2bf'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'
